version: '3'

services:
  web:
    build: .
    volumes:
      # Bind mount the working dir so any changes you make on your host OS are immediately reflected in the container
      - .:/src
      # Build output lives in a named volume so we avoid root-owned host ./_site permission issues
      - site:/tmp/jekyll-site
    ports:
      - "4000:4000"
    environment:
      - JEKYLL_DEST=/tmp/jekyll-site

volumes:
  site: